import type {
  ScreeningCase,
  OCRResult,
  ValidationResult,
  TamperingResult,
  FaceVerificationResult,
  RiskAssessment,
  DashboardStats,
  ActivityDataPoint,
  DocumentTypeCount,
} from '../types';

// ─── DEMO CASE 1: Valid Passport ──────────────────────────────────────────────

export const demoCase1: ScreeningCase = {
  id: 'demo-001',
  caseId: 'VDC-2024-001847',
  documentType: 'passport',
  officerId: 'OFF-001',
  officerName: 'Rajan Mehta',
  createdAt: '2024-09-11T08:23:15Z',
  completedAt: '2024-09-11T08:23:19Z',
  totalTimeMs: 3820,
  status: 'completed',
  demoType: 'valid',
  pipeline: [
    { id: 'upload', name: 'Document Upload', status: 'completed', durationMs: 210 },
    { id: 'preprocess', name: 'Image Preprocessing', status: 'completed', durationMs: 340 },
    { id: 'ocr', name: 'OCR Extraction', status: 'completed', durationMs: 890 },
    { id: 'validation', name: 'Document Validation', status: 'completed', durationMs: 420 },
    { id: 'tampering', name: 'Tampering Analysis', status: 'completed', durationMs: 1100 },
    { id: 'face', name: 'Face Verification', status: 'completed', durationMs: 650 },
    { id: 'risk', name: 'Risk Assessment', status: 'completed', durationMs: 210 },
  ],
  ocrResult: {
    documentType: 'passport',
    overallConfidence: 98.7,
    fields: [
      { label: 'Full Name', value: 'ARJUN SHARMA', confidence: 99.1, flagged: false },
      { label: 'Passport Number', value: 'P4729183', confidence: 98.8, flagged: false },
      { label: 'Nationality', value: 'IND', confidence: 99.5, flagged: false },
      { label: 'Date of Birth', value: '14-06-1988', confidence: 97.9, flagged: false },
      { label: 'Date of Expiry', value: '13-06-2034', confidence: 98.3, flagged: false },
      { label: 'Gender', value: 'M', confidence: 99.8, flagged: false },
      { label: 'Place of Birth', value: 'MUMBAI', confidence: 96.4, flagged: false },
      { label: 'Issuing Authority', value: 'MUMBAI REGIONAL PASSPORT OFFICE', confidence: 94.2, flagged: false },
    ],
    mrzData: {
      line1: 'P<INDSHARMAARJUN<<<<<<<<<<<<<<<<<<<<<<<<<<',
      line2: 'P47291831IND8806144M3406131<<<<<<<<<<<<6',
      parsed: {
        documentType: 'P',
        issuingCountry: 'IND',
        surname: 'SHARMA',
        givenNames: 'ARJUN',
        passportNumber: 'P4729183',
        nationality: 'IND',
        dateOfBirth: '880614',
        sex: 'M',
        expiryDate: '340613',
      }
    },
    processingTimeMs: 890,
  },
  validationResult: {
    overallStatus: 'passed',
    passedCount: 9,
    warningCount: 0,
    failedCount: 0,
    checks: [
      { id: 'v1', name: 'Passport Number Format', category: 'Format', status: 'passed', message: 'Valid Indian passport number format (P + 7 digits)' },
      { id: 'v2', name: 'Date of Birth Format', category: 'Date', status: 'passed', message: 'Date format is valid and consistent' },
      { id: 'v3', name: 'Expiry Validation', category: 'Date', status: 'passed', message: 'Document is valid until 13-Jun-2034' },
      { id: 'v4', name: 'Required Fields', category: 'Completeness', status: 'passed', message: 'All mandatory passport fields are present' },
      { id: 'v5', name: 'MRZ Consistency', category: 'MRZ', status: 'passed', message: 'MRZ data matches visible text fields' },
      { id: 'v6', name: 'Nationality Code', category: 'Format', status: 'passed', message: 'IND is a valid ISO 3166-1 alpha-3 nationality code' },
      { id: 'v7', name: 'MRZ Check Digits', category: 'MRZ', status: 'passed', message: 'All MRZ check digits verified successfully' },
      { id: 'v8', name: 'Internal Consistency', category: 'Consistency', status: 'passed', message: 'All fields are internally consistent' },
      { id: 'v9', name: 'Issue Date Validity', category: 'Date', status: 'passed', message: 'Issue date is logically valid relative to DOB and expiry' },
    ],
    processingTimeMs: 420,
  },
  tamperingResult: {
    overallRisk: 'LOW',
    overallProbability: 7,
    indicators: [
      { id: 't1', name: 'Photo Replacement', probability: 8, status: 'LOW', explanation: 'No inconsistencies detected in photo region. JPEG compression artifacts are uniform across document.' },
      { id: 't2', name: 'Text Manipulation', probability: 5, status: 'LOW', explanation: 'Font characteristics are consistent throughout. No pixel-level anomalies detected in text regions.' },
      { id: 't3', name: 'Stamp Forgery', probability: 12, status: 'LOW', explanation: 'Official stamps appear genuine. Ink density and pattern are consistent with authentic documents.' },
      { id: 't4', name: 'Image Compression Anomaly', probability: 6, status: 'LOW', explanation: 'Compression levels are uniform. No evidence of selective re-compression in specific regions.' },
      { id: 't5', name: 'Metadata Anomaly', probability: 4, status: 'LOW', explanation: 'Image metadata is consistent with an unmodified original scan.' },
    ],
    heatmapAvailable: true,
    processingTimeMs: 1100,
    disclaimer: 'Results are AI-assisted indicators only. This system does not definitively prove document authenticity or forgery. Use as one input in a multi-factor verification process.',
  },
  faceVerificationResult: {
    similarityScore: 96.3,
    isMatch: true,
    confidence: 94.8,
    explanation: 'The face in the document closely matches the provided live image. Key biometric markers including facial geometry, eye spacing, and facial structure are highly consistent.',
    faceDetectedInDocument: true,
    faceDetectedInLive: true,
    processingTimeMs: 650,
  },
  riskAssessment: {
    totalScore: 8,
    riskLevel: 'LOW',
    factors: [
      { id: 'r1', name: 'OCR Anomalies', score: 1, maxScore: 20, description: 'OCR confidence is very high across all fields.', level: 'LOW' },
      { id: 'r2', name: 'Document Validation', score: 0, maxScore: 20, description: 'All validation checks passed successfully.', level: 'LOW' },
      { id: 'r3', name: 'Tampering Probability', score: 4, maxScore: 30, description: 'Very low probability of document tampering.', level: 'LOW' },
      { id: 'r4', name: 'Face Verification', score: 2, maxScore: 25, description: 'Strong face match with high confidence.', level: 'LOW' },
      { id: 'r5', name: 'Expiry / Blacklist', score: 1, maxScore: 5, description: 'Document is valid and not on watchlist.', level: 'LOW' },
    ],
    reasons: [
      'All document validation checks passed',
      'High OCR confidence across all extracted fields',
      'Face match confirmed with 96.3% similarity',
      'No tampering indicators detected',
      'Document is within validity period',
    ],
    recommendation: 'Document appears consistent. Proceed with standard verification procedures.',
    processingTimeMs: 210,
  },
};

// ─── DEMO CASE 2: Tampered Document ──────────────────────────────────────────

export const demoCase2: ScreeningCase = {
  id: 'demo-002',
  caseId: 'VDC-2024-001848',
  documentType: 'passport',
  officerId: 'OFF-001',
  officerName: 'Rajan Mehta',
  createdAt: '2024-09-11T09:14:32Z',
  completedAt: '2024-09-11T09:14:36Z',
  totalTimeMs: 4110,
  status: 'completed',
  demoType: 'tampered',
  pipeline: [
    { id: 'upload', name: 'Document Upload', status: 'completed', durationMs: 190 },
    { id: 'preprocess', name: 'Image Preprocessing', status: 'completed', durationMs: 310 },
    { id: 'ocr', name: 'OCR Extraction', status: 'completed', durationMs: 940 },
    { id: 'validation', name: 'Document Validation', status: 'warning', durationMs: 450 },
    { id: 'tampering', name: 'Tampering Analysis', status: 'warning', durationMs: 1350 },
    { id: 'face', name: 'Face Verification', status: 'completed', durationMs: 660 },
    { id: 'risk', name: 'Risk Assessment', status: 'completed', durationMs: 210 },
  ],
  ocrResult: {
    documentType: 'passport',
    overallConfidence: 91.2,
    fields: [
      { label: 'Full Name', value: 'PRIYA NAIR', confidence: 93.4, flagged: false },
      { label: 'Passport Number', value: 'P8831204', confidence: 89.1, flagged: true },
      { label: 'Nationality', value: 'IND', confidence: 98.1, flagged: false },
      { label: 'Date of Birth', value: '22-03-1995', confidence: 85.7, flagged: true },
      { label: 'Date of Expiry', value: '21-03-2032', confidence: 90.2, flagged: false },
      { label: 'Gender', value: 'F', confidence: 99.1, flagged: false },
      { label: 'Place of Birth', value: 'KOCHI', confidence: 91.8, flagged: false },
      { label: 'Issuing Authority', value: 'KOCHI REGIONAL PASSPORT OFFICE', confidence: 88.6, flagged: false },
    ],
    mrzData: {
      line1: 'P<INDNAIR<<PRIYA<<<<<<<<<<<<<<<<<<<<<<<<<<<',
      line2: 'P88312041IND9503221F3203218<<<<<<<<<<<<4',
      parsed: {
        documentType: 'P',
        issuingCountry: 'IND',
        surname: 'NAIR',
        givenNames: 'PRIYA',
        passportNumber: 'P8831204',
        nationality: 'IND',
        dateOfBirth: '950322',
        sex: 'F',
        expiryDate: '320321',
      }
    },
    processingTimeMs: 940,
  },
  validationResult: {
    overallStatus: 'warning',
    passedCount: 6,
    warningCount: 2,
    failedCount: 1,
    checks: [
      { id: 'v1', name: 'Passport Number Format', category: 'Format', status: 'passed', message: 'Valid Indian passport number format' },
      { id: 'v2', name: 'Date of Birth Format', category: 'Date', status: 'passed', message: 'Date format is valid' },
      { id: 'v3', name: 'Expiry Validation', category: 'Date', status: 'passed', message: 'Document is within validity period' },
      { id: 'v4', name: 'Required Fields', category: 'Completeness', status: 'passed', message: 'All mandatory fields present' },
      { id: 'v5', name: 'MRZ Consistency', category: 'MRZ', status: 'failed', message: 'Date of birth mismatch between visible text and MRZ', detail: 'Visible text shows 22-03-1995 but MRZ encodes 22-03-1992', expectedValue: '22-03-1995', actualValue: 'MRZ: 22-03-1992' },
      { id: 'v6', name: 'Nationality Code', category: 'Format', status: 'passed', message: 'Valid nationality code' },
      { id: 'v7', name: 'MRZ Check Digits', category: 'MRZ', status: 'warning', message: 'Check digit inconsistency detected in date of birth field' },
      { id: 'v8', name: 'Internal Consistency', category: 'Consistency', status: 'warning', message: 'Minor inconsistency detected between field groups' },
      { id: 'v9', name: 'Issue Date Validity', category: 'Date', status: 'passed', message: 'Issue date is logically valid' },
    ],
    processingTimeMs: 450,
  },
  tamperingResult: {
    overallRisk: 'MEDIUM',
    overallProbability: 67,
    indicators: [
      { id: 't1', name: 'Photo Replacement', probability: 22, status: 'LOW', explanation: 'Minor compression inconsistencies in photo region, but within acceptable variance for legitimate documents.' },
      { id: 't2', name: 'Text Manipulation', probability: 78, status: 'HIGH', explanation: 'Significant pixel-level anomalies detected in the Date of Birth field. Font metrics deviate from surrounding text, suggesting digital editing.', region: { x: 120, y: 210, width: 180, height: 24 } },
      { id: 't3', name: 'Stamp Forgery', probability: 31, status: 'MEDIUM', explanation: 'Official stamp shows slight irregularities in ink distribution pattern. Further physical inspection recommended.' },
      { id: 't4', name: 'Image Compression Anomaly', probability: 64, status: 'MEDIUM', explanation: 'Selective re-compression artifacts detected in specific regions, inconsistent with full-document scanning.', region: { x: 100, y: 190, width: 220, height: 50 } },
      { id: 't5', name: 'Metadata Anomaly', probability: 45, status: 'MEDIUM', explanation: 'Image metadata contains inconsistent timestamp information suggesting the file may have been edited and re-saved.' },
    ],
    heatmapAvailable: true,
    processingTimeMs: 1350,
    disclaimer: 'Results are AI-assisted indicators only. This system does not definitively prove document authenticity or forgery.',
  },
  faceVerificationResult: {
    similarityScore: 88.1,
    isMatch: true,
    confidence: 82.4,
    explanation: 'The face in the document matches the provided live image with reasonable confidence. Some variance in image quality may affect score accuracy.',
    faceDetectedInDocument: true,
    faceDetectedInLive: true,
    processingTimeMs: 660,
  },
  riskAssessment: {
    totalScore: 67,
    riskLevel: 'MEDIUM',
    factors: [
      { id: 'r1', name: 'OCR Anomalies', score: 8, maxScore: 20, description: 'Low confidence in DOB and passport number fields.', level: 'MEDIUM' },
      { id: 'r2', name: 'Document Validation', score: 14, maxScore: 20, description: 'MRZ inconsistency and check digit failure detected.', level: 'HIGH' },
      { id: 'r3', name: 'Tampering Probability', score: 28, maxScore: 30, description: 'High probability of text manipulation in DOB field.', level: 'HIGH' },
      { id: 'r4', name: 'Face Verification', score: 12, maxScore: 25, description: 'Face match successful but with reduced confidence.', level: 'MEDIUM' },
      { id: 'r5', name: 'Expiry / Blacklist', score: 5, maxScore: 5, description: 'Document is valid but flagged for secondary review.', level: 'LOW' },
    ],
    reasons: [
      'Date of birth mismatch detected between visible text and MRZ zone',
      'High probability of text manipulation in DOB field (78%)',
      'Image re-compression artifacts detected in specific regions',
      'MRZ check digit inconsistency for date of birth',
      'Metadata anomalies suggest possible document editing',
    ],
    recommendation: 'Additional verification recommended. Request supporting documents and conduct manual inspection of date of birth field.',
    processingTimeMs: 210,
  },
};

// ─── DEMO CASE 3: Face Mismatch + Major Anomalies ────────────────────────────

export const demoCase3: ScreeningCase = {
  id: 'demo-003',
  caseId: 'VDC-2024-001849',
  documentType: 'passport',
  officerId: 'OFF-001',
  officerName: 'Rajan Mehta',
  createdAt: '2024-09-11T10:47:08Z',
  completedAt: '2024-09-11T10:47:12Z',
  totalTimeMs: 3940,
  status: 'completed',
  demoType: 'identity_mismatch',
  pipeline: [
    { id: 'upload', name: 'Document Upload', status: 'completed', durationMs: 180 },
    { id: 'preprocess', name: 'Image Preprocessing', status: 'completed', durationMs: 290 },
    { id: 'ocr', name: 'OCR Extraction', status: 'warning', durationMs: 1020 },
    { id: 'validation', name: 'Document Validation', status: 'failed', durationMs: 410 },
    { id: 'tampering', name: 'Tampering Analysis', status: 'warning', durationMs: 1380 },
    { id: 'face', name: 'Face Verification', status: 'failed', durationMs: 450 },
    { id: 'risk', name: 'Risk Assessment', status: 'completed', durationMs: 210 },
  ],
  ocrResult: {
    documentType: 'passport',
    overallConfidence: 76.3,
    fields: [
      { label: 'Full Name', value: 'VIKRAM DESAI', confidence: 82.1, flagged: false },
      { label: 'Passport Number', value: 'Z7294820', confidence: 71.4, flagged: true },
      { label: 'Nationality', value: 'IND', confidence: 96.2, flagged: false },
      { label: 'Date of Birth', value: '05-11-1979', confidence: 74.8, flagged: true },
      { label: 'Date of Expiry', value: '04-11-2028', confidence: 78.3, flagged: false },
      { label: 'Gender', value: 'M', confidence: 98.7, flagged: false },
      { label: 'Place of Birth', value: 'DELHI', confidence: 69.4, flagged: true },
      { label: 'Issuing Authority', value: 'DELHI RPO', confidence: 72.1, flagged: true },
    ],
    mrzData: {
      line1: 'P<INDDESAI<<VIKRAM<<<<<<<<<<<<<<<<<<<<<<<<<',
      line2: 'Z72948201IND7911054M2811041<<<<<<<<<<<<8',
      parsed: {
        documentType: 'P',
        issuingCountry: 'IND',
        surname: 'DESAI',
        givenNames: 'VIKRAM',
        passportNumber: 'Z7294820',
        nationality: 'IND',
        dateOfBirth: '791105',
        sex: 'M',
        expiryDate: '281104',
      }
    },
    processingTimeMs: 1020,
  },
  validationResult: {
    overallStatus: 'failed',
    passedCount: 4,
    warningCount: 2,
    failedCount: 3,
    checks: [
      { id: 'v1', name: 'Passport Number Format', category: 'Format', status: 'failed', message: 'Invalid passport number format: Z7294820 does not match Indian passport number pattern', detail: 'Indian passports use format: letter + 7 digits (A-Z, 0-9). Prefix Z is not valid.', expectedValue: 'P/A-Z + 7 digits', actualValue: 'Z7294820' },
      { id: 'v2', name: 'Date of Birth Format', category: 'Date', status: 'passed', message: 'Date format is valid' },
      { id: 'v3', name: 'Expiry Validation', category: 'Date', status: 'passed', message: 'Document is within validity period' },
      { id: 'v4', name: 'Required Fields', category: 'Completeness', status: 'passed', message: 'All mandatory fields present' },
      { id: 'v5', name: 'MRZ Consistency', category: 'MRZ', status: 'failed', message: 'Multiple field mismatches between visible text and MRZ', detail: 'Expiry date: visible 04-11-2028, MRZ: 04-11-2028. DOB: visible 05-11-1979, MRZ: 05-11-1979. However passport number check digit fails.', expectedValue: 'Matching', actualValue: 'Check digit mismatch' },
      { id: 'v6', name: 'Nationality Code', category: 'Format', status: 'passed', message: 'Valid nationality code' },
      { id: 'v7', name: 'MRZ Check Digits', category: 'MRZ', status: 'failed', message: 'Check digit verification failed for passport number and composite check digit' },
      { id: 'v8', name: 'Internal Consistency', category: 'Consistency', status: 'warning', message: 'Document series and issuing authority inconsistency detected' },
      { id: 'v9', name: 'Blacklist Check', category: 'Database', status: 'warning', message: '⚠ [DEMO] Passport number does not match any known valid series — flagged for review' },
    ],
    processingTimeMs: 410,
  },
  tamperingResult: {
    overallRisk: 'HIGH',
    overallProbability: 84,
    indicators: [
      { id: 't1', name: 'Photo Replacement', probability: 89, status: 'HIGH', explanation: 'Significant evidence of photo substitution detected. Compression artifacts around photo boundaries are inconsistent with the rest of the document. Photo region shows different noise signature.', region: { x: 40, y: 50, width: 120, height: 150 } },
      { id: 't2', name: 'Text Manipulation', probability: 71, status: 'HIGH', explanation: 'Multiple text regions show evidence of digital editing. Font rendering differs from authentic document templates.', region: { x: 200, y: 100, width: 280, height: 120 } },
      { id: 't3', name: 'Stamp Forgery', probability: 82, status: 'HIGH', explanation: 'Official stamps show characteristics inconsistent with genuine stamps. Pattern resolution and ink dispersion do not match standard issue documents.' },
      { id: 't4', name: 'Image Compression Anomaly', probability: 76, status: 'HIGH', explanation: 'Extensive re-compression artifacts detected across multiple regions. Inconsistent JPEG quantization tables suggest the document image was assembled from multiple sources.' },
      { id: 't5', name: 'Metadata Anomaly', probability: 93, status: 'HIGH', explanation: 'Image metadata has been stripped or modified. Creation date is inconsistent with the document issue date. Software signature indicates image editing application.' },
    ],
    heatmapAvailable: true,
    processingTimeMs: 1380,
    disclaimer: 'Results are AI-assisted indicators only. This system does not definitively prove document authenticity or forgery.',
  },
  faceVerificationResult: {
    similarityScore: 31.4,
    isMatch: false,
    confidence: 97.2,
    explanation: 'The face in the document does NOT match the provided live image. Key biometric markers including facial geometry, jawline, and eye region show significant differences. This indicates potential identity impersonation.',
    faceDetectedInDocument: true,
    faceDetectedInLive: true,
    processingTimeMs: 450,
  },
  riskAssessment: {
    totalScore: 89,
    riskLevel: 'HIGH',
    factors: [
      { id: 'r1', name: 'OCR Anomalies', score: 16, maxScore: 20, description: 'Very low OCR confidence in multiple critical fields.', level: 'HIGH' },
      { id: 'r2', name: 'Document Validation', score: 18, maxScore: 20, description: 'Multiple validation failures including passport number format and MRZ check digits.', level: 'HIGH' },
      { id: 'r3', name: 'Tampering Probability', score: 29, maxScore: 30, description: 'Very high probability of document forgery — photo replacement, text manipulation, and stamp forgery detected.', level: 'HIGH' },
      { id: 'r4', name: 'Face Verification', score: 24, maxScore: 25, description: 'Face mismatch confirmed. Live person does not match document photograph.', level: 'HIGH' },
      { id: 'r5', name: 'Expiry / Blacklist', score: 2, maxScore: 5, description: 'Document series flagged for verification.', level: 'MEDIUM' },
    ],
    reasons: [
      'FACE MISMATCH: Live person does not match document photograph (31.4% similarity)',
      'INVALID PASSPORT NUMBER: Format does not match standard Indian passport series',
      'PHOTO REPLACEMENT DETECTED: 89% probability of photograph substitution',
      'TEXT MANIPULATION DETECTED: 71% probability of digital text editing',
      'MRZ CHECK DIGIT FAILURE: Composite check digit verification failed',
      'METADATA ANOMALY: Image editing software artifacts detected',
      'STAMP FORGERY: Official stamp characteristics inconsistent with genuine documents',
    ],
    recommendation: 'Secondary manual inspection required immediately. Do not allow passage. Detain for secondary screening and notify supervisory officer.',
    processingTimeMs: 210,
  },
};

// ─── Screening History ────────────────────────────────────────────────────────

export const screeningHistory: ScreeningCase[] = [
  demoCase1,
  demoCase2,
  demoCase3,
  {
    id: 'hist-004',
    caseId: 'VDC-2024-001844',
    documentType: 'visa',
    officerId: 'OFF-002',
    officerName: 'Sunita Rao',
    createdAt: '2024-09-11T07:15:22Z',
    completedAt: '2024-09-11T07:15:26Z',
    totalTimeMs: 3620,
    status: 'completed',
    pipeline: [],
    riskAssessment: { totalScore: 12, riskLevel: 'LOW', factors: [], reasons: ['All checks passed'], recommendation: 'Proceed', processingTimeMs: 180 },
  },
  {
    id: 'hist-005',
    caseId: 'VDC-2024-001843',
    documentType: 'national_id',
    officerId: 'OFF-001',
    officerName: 'Rajan Mehta',
    createdAt: '2024-09-11T06:58:11Z',
    completedAt: '2024-09-11T06:58:14Z',
    totalTimeMs: 2890,
    status: 'completed',
    pipeline: [],
    riskAssessment: { totalScore: 4, riskLevel: 'LOW', factors: [], reasons: ['Document verified'], recommendation: 'Proceed', processingTimeMs: 140 },
  },
  {
    id: 'hist-006',
    caseId: 'VDC-2024-001840',
    documentType: 'driving_licence',
    officerId: 'OFF-003',
    officerName: 'Arun Kumar',
    createdAt: '2024-09-10T16:22:45Z',
    completedAt: '2024-09-10T16:22:49Z',
    totalTimeMs: 3100,
    status: 'completed',
    pipeline: [],
    riskAssessment: { totalScore: 44, riskLevel: 'MEDIUM', factors: [], reasons: ['Expiry date inconsistency'], recommendation: 'Additional verification recommended', processingTimeMs: 190 },
  },
  {
    id: 'hist-007',
    caseId: 'VDC-2024-001837',
    documentType: 'passport',
    officerId: 'OFF-002',
    officerName: 'Sunita Rao',
    createdAt: '2024-09-10T15:10:33Z',
    completedAt: '2024-09-10T15:10:37Z',
    totalTimeMs: 4200,
    status: 'completed',
    pipeline: [],
    riskAssessment: { totalScore: 77, riskLevel: 'HIGH', factors: [], reasons: ['Photo replacement', 'Face mismatch'], recommendation: 'Secondary inspection required', processingTimeMs: 220 },
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalScreened: 1849,
  suspicious: 247,
  highRisk: 89,
  verified: 1602,
  avgScreeningTimeMs: 3750,
  todayScreened: 47,
};

export const activityData: ActivityDataPoint[] = [
  { date: 'Sep 5', low: 38, medium: 8, high: 3 },
  { date: 'Sep 6', low: 42, medium: 11, high: 4 },
  { date: 'Sep 7', low: 35, medium: 7, high: 2 },
  { date: 'Sep 8', low: 51, medium: 14, high: 6 },
  { date: 'Sep 9', low: 44, medium: 9, high: 3 },
  { date: 'Sep 10', low: 39, medium: 12, high: 5 },
  { date: 'Sep 11', low: 33, medium: 8, high: 6 },
];

export const documentTypeData: DocumentTypeCount[] = [
  { type: 'Passport', count: 1124 },
  { type: 'Visa', count: 412 },
  { type: 'National ID', count: 187 },
  { type: 'Driving Licence', count: 94 },
  { type: 'Permit', count: 32 },
];

export const riskDistributionData = [
  { name: 'Low Risk', value: 1602, color: '#10b981' },
  { name: 'Medium Risk', value: 158, color: '#f59e0b' },
  { name: 'High Risk', value: 89, color: '#ef4444' },
];

// ─── Demo Officer ─────────────────────────────────────────────────────────────

export const demoOfficer = {
  id: '1',
  officerId: 'OFF-001',
  name: 'Rajan Mehta',
  rank: 'Senior Border Security Officer',
  unit: 'CISF — International Border Unit',
  lastLogin: '2024-09-11T06:00:00Z',
};
